Add support for capturing DOIs with trailing (selective) punctionation
altmetric/identifiers pull request #8
Opened 2017-04-05 10:04 UTC by shamess

This comes with trade offs of course.

The downside of this PR is that this example will incorrectly pick up the closing bracket:

> "(for more information, see the DOI 10.2345/somedoiorother)"

The upside is that we now correctly pick up this DOI:

> 10.1130/2013.2502(04)

2017-04-05 10:20 UTC, cwrw requested changes

2017-04-05 10:20 UTC, cwrw commented on CHANGELOG.md
> +### Changed
regarding bumping up the version and changelog etc, there are a few other places to look at, see https://github.com/altmetric/identifiers/commit/53ceb69d4de655ee86fe4bf4b7e4ad953b5e1029

2017-04-05 10:20 UTC, cwrw commented on spec/identifiers/doi_spec.rb
> +    str = 'This is an example of DOI - 10.1049/el.2013.3006 - which is entirely valid'
was this not already enabled?

2017-04-05 10:22 UTC, shamess commented on spec/identifiers/doi_spec.rb
> +    str = 'This is an example of DOI - 10.1049/el.2013.3006 - which is entirely valid'
It was, but there was no test for "in the middle of a string". Since I was tweaking that kind of code, I wanted to double check it continued to work.

2017-04-05 10:27 UTC, mudge commented
Do we have a sense (e.g. from our own internal projects) how many DOIs we find with closing parentheses at the end of them vs DOIs in a parenthetical statement in some larger text?

It may well be that this isn't worth the added complexity as we lose the recall picking up DOIs in regular text.

Having said that: what if we extracted _two_ DOIs when seeing something with trailing punctuation?

e.g.

```ruby
Identifiers::DOI.extract('10.1234/foo(bar)')
#=> ['10.1234/foo(bar)', '10.1234/foo(bar']
Identifiers::DOI.extract('10.1234/foo.bar.')
#=> ['10.1234/foo.bar.', '10.1234/foo.bar']
```

The risk here would be that two wholly distinct DOIs exist that are separated only by trailing punctuation.

2017-04-08 10:04 UTC, mudge commented
Superseded by #9

2017-04-08 10:04 UTC, closed without merging